version: 2
jobs:
  build:
    docker:
    - image: manimaul/libevent-builder:stretch
    steps:
    - checkout
    - run:
        name: Build
        command: |
          git submodule update --init --recursive
          mkdir build
          pushd build
          cmake ..
          make
          popd
    - run:
        name: GTests
        command: ./build/runUnitTests
