version: 2
jobs:
  build:
    docker:
    - image: manimaul/libevent-builder:stretch
    steps:
    - checkout
    - run:
        name: Build
        command: |
          git submodule update --init --recursive
          mkdir build
          pushd build
          LE_EXAMPLE=1 GTEST=1 cmake ..
          make install
          popd
    - run:
        name: GTests
        command: /usr/local/bin/runUnitTests
    - run:
        name: Py Integration Tests
        command: |
          pushd py_int_test
          apt-get -y install python3 python3-pip python3-pycurl
          pip3 install -r requirements.txt
          /usr/local/bin/lehttp_example & python3 int_test.py
          popd
